### ISSUE TITLE
no englesh i russian

### ISSUE THREAD

**Issue by ruslan4us** [Eastonn/Visible#2]
hi я руслан. куда ставить файл и как инжектить в dll ? подробнее можете рассказать? 2 месяца назад последний файл - что с ним делать объясните

**Comment by Eastonn** [comment]
Привет, чит не обновлялся, поэтому никак не инжектнуть DLL, которая релизнута, еще мне говорили, что после последнего комита билд сломался. В общем, обновлять я не планирую, можешь взять прошлую версию и сам это сделать
